master [v0.0.7]  auto assembly first attempt

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -10,19 +10,20 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-latest
-    name: "Build ${{ github.ref }}"
+    name: "Build  [${{ matrix.os }}]"
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ ubuntu-latest, macos-latest, windows-latest, ubuntu-20.04, macos-12, windows-2019, windows-2022 ]
+    permissions:
+      contents: write
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-
       ########################################################################################################################
 
       - name: Load Info from Build
+        if: ${{ matrix.os == 'ubuntu-latest' }}
         run: |
           nameBuild=$(./_run/scripts/sys.sh -n)
           versionBuild=$(./_run/scripts/sys.sh -v)
@@ -33,12 +34,21 @@ jobs:
           echo "NAME: $nameBuild"
           echo "VER: $versionBuild"
 
-      - name: Check Tag
+      - name: Check Tag [linux]
+        if: ${{ matrix.os == 'ubuntu-latest'}}
         run: |
           if [[ "${{ github.event.release.tag_name }}" != "${{ env.BUILD_VER }}" ]]; then
             curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             "https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}"
           
+            echo "::error ::Incorrect release tag. Should match the [${{ env.BUILD_VER }}]."
+            exit 1
+          fi
+
+      - name: Check Tag [other]
+        if: ${{ matrix.os != 'ubuntu-latest'}}
+        run: |
+          if [[ "${{ github.event.release.tag_name }}" != "${{ env.BUILD_VER }}" ]]; then
             echo "::error ::Incorrect release tag. Should match the [${{ env.BUILD_VER }}]."
             exit 1
           fi
@@ -52,15 +62,46 @@ jobs:
             exit 1
           fi
 
-      - name: Push new version
+      ########################################################################################################################
+
+      - name: Run build
+        run: go build -o esptool
+
+
+      - name: Save [linux] build
+        if: ${{ matrix.os != 'windows-latest' && matrix.os != 'windows-2022' && matrix.os != 'windows-2019' }}
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ github.event.release.upload_url }}
+          asset_path: esptool
+          asset_name: "${{ env.BUILD_NAME }}.${{ env.BUILD_VER }}.linux.bin"
+          asset_content_type: application/octet-stream
+
+      - name: Save [win] build
+        if:  ${{ matrix.os == 'windows-latest' || matrix.os == 'windows-2022' || matrix.os == 'windows-2019' }}
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ github.event.release.upload_url }}
+          asset_path: esptool
+          asset_name: "${{ env.BUILD_NAME }}.${{ env.BUILD_VER }}.windows.exe"
+          asset_content_type: application/octet-stream
+
+   ########################################################################################################################
+
+      - name: Push new version [linux]
+        if: ${{ matrix.os == 'ubuntu-latest'}}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           new_version=$(./_run/scripts/sys.sh --increment --minor)
-          
+
           git add ./_run/values/ver.txt
-          
+
           git commit -m "actions [$new_version] "$'\n'"Build: [${{ env.BUILD_VER }}] >> [$new_version]"
           git push origin HEAD:main
